services:
  # A Docker web service
  - type: web
    name: mastodon
    repo: https://github.com/mastodon/mastodon.git
    env: ruby
    region: oregon # optional (defaults to oregon)
    plan: standard # optional (defaults to starter)
    buildCommand: bundle install
    numInstances: 1 # optional (defaults to 1)
    healthCheckPath: /health
    envVars:
      - fromGroup: rails-secrets
      - fromGroup: mastodon-settings
      - key: DATABASE_URL
        fromDatabase:
          name: mastodon-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: mastodon-redis
          property: connectionString
          property: connectionString
  - type: redis
    name: mastodon-redis
    ipAllowList: []
    plan: starter # optional (defaults to starter)
    maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

databases:
  - name: mastodon-db
    ipAllowList: []

envVarGroups:
  - name: mastodon-settings
    envVars:
      - key: RAILS_ENV
        value: production
